


CREATE TABLE EMPLEADOS_BVVA(
ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(100) NOT NULL,
APP NVARCHAR2(100) NOT NULL,
APM NVARCHAR2(100),
FECHA_NACI DATE NOT NULL,
CORREO NVARCHAR2(70) NOT NULL 
);

SELECT * FROM EMPLEADOS_BVVA;
